<div style="background:#1A1D1D; padding:26px 30px; border-radius:8px;">
<div style="display:inline-block; background:#F05E22; color:#fff; font-family:Calibri,sans-serif;
     font-size:11px; font-weight:bold; letter-spacing:1px; padding:5px 12px; border-radius:12px;">
DAY 6 OF 120</div>
<h1 style="color:#fff; font-family:Cambria,Georgia,serif; margin:14px 0 2px 0; font-size:34px;">
NumPy <span style="color:#F05E22;">Fundamentals</span></h1>
<p style="color:#9D9E9E; font-family:Calibri,sans-serif; font-size:14px; margin:8px 0 0 0;">
Vectorisation, arrays, indexing, boolean masking, and the one that matters most — broadcasting.</p>
<p style="color:#F05E22; font-family:Calibri,sans-serif; font-size:12px; margin:14px 0 0 0;">
Phase 1 · Week 2 · Day 6 &nbsp;·&nbsp; 90-minute concept session</p>
</div>



Week 1 taught you Python and how to write it professionally. Week 2 is about *numbers* — and
everything numerical in machine learning sits on NumPy.

> **Why this matters:** PyTorch tensors, Pandas DataFrames, scikit-learn inputs, and every image you
> feed a model are NumPy arrays or built on the same ideas. If arrays and broadcasting are shaky,
> every day from here is harder.


In [1]:
import numpy as np

print("numpy version:", np.__version__)

numpy version: 2.3.5


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 1 &nbsp;·&nbsp; ~8 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Why NumPy exists</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Vectorisation: the loop moves from Python into C.</p>
</div>

> **Vectorisation** — performing an operation on an entire array at once, instead of looping over
> elements one at a time. The loop still happens; it happens down in compiled C rather than in Python,
> without interpreter overhead on every iteration.

Let's measure rather than take my word for it.

In [2]:
import timeit

N = 1_000_000
setup = f"import numpy as np; lst = list(range({N})); arr = np.arange({N})"

py_time = timeit.timeit("[x * 2 for x in lst]", setup=setup, number=10) / 10
np_time = timeit.timeit("arr * 2", setup=setup, number=10) / 10

print(f"Python list comprehension: {py_time * 1000:7.2f} ms")
print(f"NumPy vectorised:          {np_time * 1000:7.2f} ms")
print(f"NumPy is about {py_time / np_time:.0f}x faster")

Python list comprehension:   43.16 ms
NumPy vectorised:             2.02 ms
NumPy is about 21x faster


Expect roughly 30–60x depending on your machine. You will sometimes see "100x" quoted — achievable on
some operations and hardware, but not a promise. The honest claim: **vectorised NumPy is dramatically
faster, and the gap grows with size.**

<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">We're about to time the same operation at 1,000 / 10,000 / 100,000 / 1,000,000 elements. Will the speedup be roughly constant, or will it change with size?</p>
</div>

In [37]:
import numpy as np
import timeit

for n in [1_000, 10_000, 100_000, 1_000_000]:
    setup = f"import numpy as np; lst = list(range({n})); arr = np.arange({n})"
    py = timeit.timeit("[x * 2 for x in lst]", setup=setup, number=20) / 20
    npt = timeit.timeit("arr * 2", setup=setup, number=20) / 20
    print(f"n = {n:>9,}   python {py*1000:7.2f} ms   numpy {npt*1000:6.3f} ms   {py/npt:5.0f}x")

n =     1,000   python    0.04 ms   numpy  0.003 ms      13x
n =    10,000   python    0.27 ms   numpy  0.018 ms      15x
n =   100,000   python    4.26 ms   numpy  0.040 ms     107x
n = 1,000,000   python   40.01 ms   numpy  1.661 ms      24x


At small sizes the advantage is modest — NumPy pays a fixed setup cost per operation. At a million
elements it is enormous. **Vectorise when data is big; do not convert a 5-element list to an array.**

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 2 &nbsp;·&nbsp; ~6 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Creating arrays</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Five ways you'll use constantly.</p>
</div>

> **ndarray** — NumPy's core type: an N-dimensional array whose elements are all the *same* type,
> stored in one contiguous block of memory. That uniformity is what makes it fast.

In [4]:
import numpy as np

print("from a list:      ", np.array([1, 2, 3, 4, 5]))
print("arange(0, 10, 2): ", np.arange(0, 10, 2))     # start, stop, step
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))    # start, stop, how many
print("zeros(5):         ", np.zeros(5))
print("ones(3):          ", np.ones(3))
print("full(4, 7):       ", np.full(4, 7))

from a list:       [1 2 3 4 5]
arange(0, 10, 2):  [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
zeros(5):          [0. 0. 0. 0. 0.]
ones(3):           [1. 1. 1.]
full(4, 7):        [7 7 7 7]


**`arange` vs `linspace`** — constantly confused:
- `arange(start, stop, step)` — you control the **step size**; stop is **excluded**
- `linspace(start, stop, num)` — you control **how many points**; stop is **included**

In [5]:
import numpy as np

print("arange(0, 1, 0.25):", np.arange(0, 1, 0.25))   # no 1.0 -- stop excluded
print("linspace(0, 1, 5): ", np.linspace(0, 1, 5))    # has 1.0 -- stop included

arange(0, 1, 0.25): [0.   0.25 0.5  0.75]
linspace(0, 1, 5):  [0.   0.25 0.5  0.75 1.  ]


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 3 &nbsp;·&nbsp; ~7 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">shape, ndim, size</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">The first thing to check when anything breaks.</p>
</div>

> **shape** — a tuple giving the size along each dimension.
> **ndim** — how many dimensions.
> **size** — total number of elements.

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3],
              [4, 5, 6]])
c = np.zeros((2, 3, 4))

for name, arr in [("a (1D)", a), ("b (2D)", b), ("c (3D)", c)]:
    print(f"{name}: shape={str(arr.shape):12} ndim={arr.ndim}  size={arr.size}")

a (1D): shape=(6,)         ndim=1  size=6
b (2D): shape=(2, 3)       ndim=2  size=6
c (3D): shape=(2, 3, 4)    ndim=3  size=24


Read `shape` carefully. `b.shape` is `(2, 3)` — **2 rows, 3 columns**. The first number is always the
outermost dimension.

For `c` with shape `(2, 3, 4)`: 2 blocks, each of 3 rows, each row 4 elements. That is exactly how an
image batch is shaped in deep learning — `(batch, height, width)`.

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 4 &nbsp;·&nbsp; ~7 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">dtype — and why it matters in ML</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Every element is the same type. NumPy picks one if you don't.</p>
</div>

In [8]:
import numpy as np

ints = np.array([1, 2, 3])
floats = np.array([1.0, 2.0, 3.0])
mixed = np.array([1, 2.5, 3])          # ONE float makes them ALL floats

print("ints:  ", ints, ints.dtype)
print("floats:", floats, floats.dtype)
print("mixed: ", mixed, mixed.dtype, "  <- promoted")

ints:   [1 2 3] int64
floats: [1. 2. 3.] float64
mixed:  [1.  2.5 3. ] float64   <- promoted


<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">np.array([1, 2, 3]) is an integer array. What dtype does dividing it by 2 give — int or float?</p>
</div>

In [9]:
import numpy as np

int_arr = np.array([1, 2, 3])
result = int_arr / 2

print("int_arr / 2 =", result)
print("dtype:", result.dtype, " <- division ALWAYS produces float")

# integer division keeps ints
print("\nint_arr // 2 =", int_arr // 2, "dtype:", (int_arr // 2).dtype)

int_arr / 2 = [0.5 1.  1.5]
dtype: float64  <- division ALWAYS produces float

int_arr // 2 = [0 1 1] dtype: int64


In [10]:
import numpy as np

# memory: float32 is half the size of float64
big64 = np.ones(1_000_000, dtype=np.float64)
big32 = np.ones(1_000_000, dtype=np.float32)

print(f"float64: {big64.nbytes / 1e6:.1f} MB")
print(f"float32: {big32.nbytes / 1e6:.1f} MB")
print("\nPyTorch defaults to float32 for exactly this reason.")

float64: 8.0 MB
float32: 4.0 MB

PyTorch defaults to float32 for exactly this reason.


On a large dataset or a GPU, that halving is the difference between fitting in memory and not.

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 5 &nbsp;·&nbsp; ~5 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">1D indexing and slicing</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Works like a Python list. Quick refresher.</p>
</div>

In [11]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("a[0]    :", a[0])       # first
print("a[-1]   :", a[-1])      # last
print("a[1:4]  :", a[1:4])     # slice, stop excluded
print("a[:3]   :", a[:3])
print("a[::2]  :", a[::2])     # every 2nd
print("a[::-1] :", a[::-1])    # reversed

a[0]    : 10
a[-1]   : 50
a[1:4]  : [20 30 40]
a[:3]   : [10 20 30]
a[::2]  : [10 30 50]
a[::-1] : [50 40 30 20 10]


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 6 &nbsp;·&nbsp; ~8 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">2D indexing — the comma changes everything</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">arr[row, col], and : means 'all of this axis'.</p>
</div>

In [12]:
import numpy as np

grid = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
print(grid)
print("\nshape:", grid.shape, "-> 3 rows, 4 columns")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4) -> 3 rows, 4 columns


In [13]:
import numpy as np

grid = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])

print("grid[1, 2] ->", grid[1, 2], "   one element: row 1, col 2")
print("grid[0]    ->", grid[0], " the whole first row")
print("grid[:, 1] ->", grid[:, 1], " the whole column 1")

grid[1, 2] -> 7    one element: row 1, col 2
grid[0]    -> [1 2 3 4]  the whole first row
grid[:, 1] -> [ 2  6 10]  the whole column 1


**The comma is the key idea.** `grid[1, 2]` = row 1, column 2. Compare a list-of-lists, where you'd
write `grid[1][2]`. NumPy's comma syntax extends to any number of dimensions, and `:` means
"everything along this axis".

`grid[:, 1]` = "every row, column 1" = an entire column. You will write that hundreds of times.

<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">grid[1:, 2:] — which part of the 3x4 grid does this select? Describe it before we run it.</p>
</div>

In [14]:
import numpy as np

grid = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])

print("grid[1:, 2:] -> rows from 1 onward, columns from 2 onward:")
print(grid[1:, 2:])

grid[1:, 2:] -> rows from 1 onward, columns from 2 onward:
[[ 7  8]
 [11 12]]


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 7 &nbsp;·&nbsp; ~7 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Views vs copies — a real trap</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">NumPy slices share memory. Python lists don't.</p>
</div>

<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">We slice an array, change the slice, then print the ORIGINAL. Does the original change?</p>
</div>

In [15]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])
piece = original[1:4]
piece[0] = 999

print("piece   :", piece)
print("original:", original, "  <-- CHANGED. slices share memory")

piece   : [999   3   4]
original: [  1 999   3   4   5]   <-- CHANGED. slices share memory


In [38]:
import numpy as np

# .copy() gives you independence
original = np.array([1, 2, 3, 4, 5])
safe = original[1:4].copy()
safe[0] = 999

print("safe    :", safe)
print("original:", original, "  <-- untouched")

# contrast with a Python list, which copies on slice
py = [1, 2, 3, 4, 5]
py_piece = py[1:4]
py_piece[0] = 999
print("\npython list original:", py, "  <-- lists COPY on slice")

safe    : [999   3   4]
original: [1 2 3 4 5]   <-- untouched

python list original: [1, 2, 3, 4, 5]   <-- lists COPY on slice


This is a **major** difference from Python lists. NumPy slices are *views* — fast and memory-efficient,
but they will bite you if unexpected. It's the array version of Day 2's mutability trap.

**Rule of thumb:** if you're going to modify a slice and need the original intact, `.copy()`.

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 8 &nbsp;·&nbsp; ~9 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Boolean masking — filtering without loops</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">How you filter data in NumPy and Pandas.</p>
</div>

> **Boolean mask** — an array of `True`/`False` the same shape as your data, used to select elements.

In [17]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67, 40, 78])

mask = scores >= 60          # a comparison produces booleans
print("scores:", scores)
print("mask:  ", mask)
print("\nselected:", scores[mask])
print("one-liner:", scores[scores >= 60])

scores: [45 88 32 91 67 40 78]
mask:   [False  True False  True  True False  True]

selected: [88 91 67 78]
one-liner: [88 91 67 78]


In [18]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67, 40, 78])

# combine with & (and), | (or), ~ (not) -- parentheses REQUIRED
print("between 40 and 80:", scores[(scores >= 40) & (scores <= 80)])
print("below 40 or above 85:", scores[(scores < 40) | (scores > 85)])
print("NOT passing:", scores[~(scores >= 60)])

between 40 and 80: [45 67 40 78]
below 40 or above 85: [88 32 91]
NOT passing: [45 32 40]


Two things to burn in:

1. **Use `&`, `|`, `~` — never `and`, `or`, `not`.** The Python keywords try to reduce a whole array to
   one True/False and fail.
2. **Parentheses are mandatory.** `scores >= 40 & scores <= 80` breaks because `&` binds tighter
   than `>=`.

In [39]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67, 40, 78])

# the error you get with 'and'
try:
    scores[(scores >= 40) and (scores <= 80)]
except ValueError as e:
    print("ValueError:", str(e)[:70], "...")

ValueError: The truth value of an array with more than one element is ambiguous. U ...


<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">Since True == 1, what do you think mask.sum() and mask.mean() give you?</p>
</div>

In [20]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67, 40, 78])
mask = scores >= 60

print("how many passed?", mask.sum())          # True == 1, so sum counts
print("what fraction?  ", f"{mask.mean():.1%}")  # mean gives the proportion

how many passed? 4
what fraction?   57.1%


That trick — `.sum()` to **count** and `.mean()` to get a **proportion** — you will use constantly.

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 9 &nbsp;·&nbsp; ~5 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">np.where — vectorised if/else</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Conditional logic without a loop.</p>
</div>

In [21]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67])

labels = np.where(scores >= 60, "PASS", "FAIL")
print(scores)
print(labels)

[45 88 32 91 67]
['FAIL' 'PASS' 'FAIL' 'PASS' 'PASS']


In [22]:
import numpy as np

scores = np.array([45, 88, 32, 91, 67])

# also transforms values: raise anything under 50 up to 50
floored = np.where(scores < 50, 50, scores)
print("original:", scores)
print("floored: ", floored)

original: [45 88 32 91 67]
floored:  [50 88 50 91 67]


Read it as: `np.where(condition, value_if_true, value_if_false)` — applied elementwise across the
whole array.

---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 10 &nbsp;·&nbsp; ~9 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Aggregation and the axis argument</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">The single most common source of small NumPy bugs.</p>
</div>

In [23]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid, "\nshape:", grid.shape)

print("\ngrid.sum()       ->", grid.sum(), " everything")
print("grid.min(), max() ->"), grid.min(), grid.max()

[[1 2 3]
 [4 5 6]] 
shape: (2, 3)

grid.sum()       -> 21  everything
grid.min(), max() -> 1 6


> **axis** — which dimension to *collapse*. `axis=0` collapses down the rows (giving one value per
> **column**). `axis=1` collapses across the columns (one value per **row**).

The wording trips everyone. The reliable way to remember: **the axis you name is the one that
disappears.**

<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">grid is shape (2, 3). What shape does grid.sum(axis=0) have — and does it give 2 numbers or 3?</p>
</div>

In [24]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

col_sums = grid.sum(axis=0)     # axis 0 (size 2) disappears -> 3 left
row_sums = grid.sum(axis=1)     # axis 1 (size 3) disappears -> 2 left

print("grid.sum(axis=0) =", col_sums, " shape", col_sums.shape, " <- per column")
print("grid.sum(axis=1) =", row_sums, " shape", row_sums.shape, " <- per row")

grid.sum(axis=0) = [5 7 9]  shape (3,)  <- per column
grid.sum(axis=1) = [ 6 15]  shape (2,)  <- per row


`(2, 3)` with `axis=0` → the 2 vanishes → shape `(3,)`. Check the shape of the result and you can
never get this wrong.

In [25]:
import numpy as np

# same idea, real data: 4 students x 3 exams
marks = np.array([[80, 70, 90],
                  [60, 65, 70],
                  [95, 88, 92],
                  [50, 45, 60]])

print("per-student average (axis=1):", marks.mean(axis=1))
print("per-exam average    (axis=0):", marks.mean(axis=0))

per-student average (axis=1): [80.         65.         91.66666667 51.66666667]
per-exam average    (axis=0): [71.25 67.   78.  ]


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 11 &nbsp;·&nbsp; ~12 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Broadcasting — the most important idea today</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Making different shapes work together.</p>
</div>

> **Broadcasting** — NumPy's rules for combining arrays of *different shapes*, by automatically
> stretching the smaller across the larger without copying memory.

You've already used it without noticing.

In [26]:
import numpy as np

a = np.array([1, 2, 3, 4])

# 10 is a single number -- stretched across all four elements
print("a * 10  =", a * 10)
print("a + 100 =", a + 100)

a * 10  = [10 20 30 40]
a + 100 = [101 102 103 104]


### The rule

Compare shapes **from the right**. Two dimensions are compatible if they are **equal**, or one of them
is **1**. Otherwise: error.

```
    (3, 4)          (3, 4)          (3, 4)
    (   4)   OK     (3, 1)   OK     (   3)   ERROR
   -------         -------         -------
    (3, 4)          (3, 4)          4 vs 3 -- neither equal nor 1
```

In [27]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])          # (2, 3)

row = np.array([10, 20, 30])          # (3,) -> stretched DOWN the rows
print("grid + row:")
print(grid + row)

grid + row:
[[11 22 33]
 [14 25 36]]


In [28]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])          # (2, 3)

col = np.array([[100],
                [200]])               # (2, 1) -> stretched ACROSS the columns
print("grid + col:")
print(grid + col)

grid + col:
[[101 102 103]
 [204 205 206]]


<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">grid is (2,3). We add an array of shape (2,). Compatible or error? Compare from the right.</p>
</div>

In [29]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])          # (2, 3)
bad = np.array([1, 2])                # (2,) -> compares 3 vs 2 -- FAILS

try:
    grid + bad
except ValueError as e:
    print("ValueError:", e)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 


In [30]:
import numpy as np

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
bad = np.array([1, 2])

# fix: reshape (2,) into (2,1) so it stretches across columns
fixed = bad.reshape(2, 1)
print("reshaped to:", fixed.shape)
print(grid + fixed)

reshaped to: (2, 1)
[[2 3 4]
 [6 7 8]]


### A real use: standardising features

Broadcasting doing actual ML work — centring each column by subtracting its mean.

In [31]:
import numpy as np

# 4 samples, 3 features -- note the wildly different scales
data = np.array([[10.0, 200.0, 3.0],
                 [20.0, 300.0, 5.0],
                 [30.0, 100.0, 7.0],
                 [40.0, 400.0, 9.0]])

col_means = data.mean(axis=0)     # (3,) -- one per feature
col_stds = data.std(axis=0)

print("data shape: ", data.shape)
print("means shape:", col_means.shape, "->", col_means)

standardised = (data - col_means) / col_stds     # (4,3) - (3,) broadcasts

print("\nstandardised:")
print(np.round(standardised, 3))
print("\ncolumn means now:", np.round(standardised.mean(axis=0), 10))
print("column stds now: ", np.round(standardised.std(axis=0), 10))

data shape:  (4, 3)
means shape: (3,) -> [ 25. 250.   6.]

standardised:
[[-1.342 -0.447 -1.342]
 [-0.447  0.447 -0.447]
 [ 0.447 -1.342  0.447]
 [ 1.342  1.342  1.342]]

column means now: [0. 0. 0.]
column stds now:  [1. 1. 1.]


That's **feature standardisation** — done before nearly every model in Phase 2. Three lines, no loops,
works on four rows or four million.

In [32]:
import numpy as np

# another classic: a multiplication table, no loops
rows = np.arange(1, 6).reshape(-1, 1)    # (5, 1)
cols = np.arange(1, 6)                   # (5,)

print("(5,1) * (5,) broadcasts to (5,5):")
print(rows * cols)

(5,1) * (5,) broadcasts to (5,5):
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


---
<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:10px 16px; border-radius:4px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">SECTION 12 &nbsp;·&nbsp; ~7 MIN</span>
<h2 style="font-family:Cambria,Georgia,serif; color:#1A1D1D; margin:4px 0 2px 0;">Reshaping</h2>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#5F5F60; margin:0;">Rearranging without changing the data.</p>
</div>

In [33]:
import numpy as np

a = np.arange(12)
print("original:", a, "shape", a.shape)

print("\nreshape(3, 4):")
print(a.reshape(3, 4))

print("\nreshape(4, -1) -> shape", a.reshape(4, -1).shape, "  (-1 means 'work it out')")
print("ravel() flattens back:", a.reshape(3, 4).ravel())

original: [ 0  1  2  3  4  5  6  7  8  9 10 11] shape (12,)

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(4, -1) -> shape (4, 3)   (-1 means 'work it out')
ravel() flattens back: [ 0  1  2  3  4  5  6  7  8  9 10 11]


<div style="background:#1A1D1D; padding:12px 18px; border-radius:5px;">
<span style="font-family:Calibri,sans-serif; font-size:11px; color:#F05E22; font-weight:bold;
letter-spacing:1px;">PREDICT FIRST</span>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#fff; margin:5px 0 0 0;">scikit-learn often demands 2D input even for one feature. How do you turn shape (3,) into a column of shape (3,1)?</p>
</div>

In [34]:
import numpy as np

a = np.array([1, 2, 3])

print("a shape:               ", a.shape)
print("a.reshape(-1, 1) shape:", a.reshape(-1, 1).shape, " <- column vector")
print(a.reshape(-1, 1))

a shape:                (3,)
a.reshape(-1, 1) shape: (3, 1)  <- column vector
[[1]
 [2]
 [3]]


`reshape(-1, 1)` is one of the most-typed lines in ML code. Remember it.

---
## Putting it together

One realistic problem using everything above — and not a single Python loop.

In [35]:
import numpy as np

rng = np.random.default_rng(7)      # seeded -> reproducible

students = np.array(["Asha", "Ravi", "Meera", "Dev", "Priya"])
marks = rng.integers(35, 100, size=(5, 4))       # 5 students x 4 exams

print("marks:")
print(marks)

per_student = marks.mean(axis=1)                 # collapse exams
per_exam = marks.mean(axis=0)                    # collapse students

print("\nper-student average:", np.round(per_student, 1))
print("per-exam average:   ", np.round(per_exam, 1))

passed = per_student >= 60                       # boolean mask
print("\npassed:", students[passed])
print("failed:", students[~passed])

best = per_student.argmax()                      # argmax gives the INDEX
print(f"\ntop student: {students[best]} ({per_student[best]:.1f})")
print(f"hardest exam: exam {per_exam.argmin() + 1} (avg {per_exam.min():.1f})")

marks:
[[96 75 79 93]
 [72 85 89 49]
 [38 54 53 91]
 [94 35 67 88]
 [43 86 42 65]]

per-student average: [85.8 73.8 59.  71.  59. ]
per-exam average:    [68.6 67.  66.  77.2]

passed: ['Asha' 'Ravi' 'Dev']
failed: ['Meera' 'Priya']

top student: Asha (85.8)
hardest exam: exam 3 (avg 66.0)


In [36]:
import numpy as np

rng = np.random.default_rng(7)
marks = rng.integers(35, 100, size=(5, 4))

# curve everyone +5, cap at 100 -- broadcasting + clip
curved = np.clip(marks + 5, 0, 100)
capped = ((marks + 5) > 100).sum()

print("curved (+5, capped at 100):")
print(curved)
print(f"\nmarks that hit the cap: {capped}")

curved (+5, capped at 100):
[[100  80  84  98]
 [ 77  90  94  54]
 [ 43  59  58  96]
 [ 99  40  72  93]
 [ 48  91  47  70]]

marks that hit the cap: 1


---
## Recap

| Idea | Syntax | Why it matters |
|---|---|---|
| Create | `np.array`, `arange`, `linspace`, `zeros` | Getting data in |
| Inspect | `.shape`, `.dtype`, `.ndim` | Every bug starts here |
| Index 2D | `arr[row, col]`, `arr[:, 1]` | Rows and columns |
| Views | `.copy()` when you need independence | Silent bugs otherwise |
| Mask | `arr[arr > 5]`, `&`, `\|`, `~` | Filtering, no loops |
| Count | `mask.sum()`, `mask.mean()` | True == 1 |
| Conditional | `np.where(cond, a, b)` | Vectorised if/else |
| Aggregate | `.mean(axis=0)` vs `axis=1` | The named axis disappears |
| Broadcasting | shapes align from the right | The core idea |
| Reshape | `.reshape(-1, 1)` | Making shapes fit |

### The two things to remember

1. **Never write a Python loop over an array.** If you're looping, there's a vectorised way — and it
   will be dramatically faster.
2. **When something breaks, print the shapes first.** Nine out of ten NumPy errors are shape errors.

<div style="background:#FDF0E9; border-left:4px solid #F05E22; padding:16px 20px; border-radius:5px;">
<b style="color:#F05E22; font-family:Calibri,sans-serif;">Now open the task sheet</b>
<p style="font-family:Calibri,sans-serif; font-size:13px; color:#1A1D1D; margin:6px 0 0 0;">
15 array puzzles, your own loop-vs-vectorised timing comparison, broadcasting exercises with
mismatched shapes, and visualising a 2D array as an image.</p>
</div>